-- Combining text tables

SELECT orig.review_id AS review_id,
orig.target_ufc_bool AS target_clf,
orig.target_ufc_count AS target_reg,
orig.review_stars AS review_stars,
nb.NB_tfidf_true_prob AS nb_prob,
svm.svm_pred AS svm_pred,
ft.ft_quality_prob AS ft_prob,
lda.topic_0_lda AS lda_t1,
lda.topic_1_lda AS lda_t2,
lda.topic_2_lda AS lda_t3,
lda.topic_3_lda AS lda_t4,
lda.topic_4_lda AS lda_t5,
base.grade_level AS grade_level,
base.polarity AS polarity,
base.subjectivity AS subjectivity,
base.word_count AS word_cnt,
base.character_count AS character_cnt,
base.num_count AS num_cnt,
base.uppercase_count AS uppercase_cnt,
base.#_@_count AS #@_cnt,
base.sentence_count AS sentence_cnt,
base.lexicon_count AS lexicon_cnt,
base.syllable_count AS syllable_cnt,
base.avg_word_length AS avg_word_len,
spy.token_count AS token_cnt,
spy.stopword_count AS stopword_cnt,
spy.stopword_perc AS stopword_pct,
spy.ent_count AS ent_cnt,
spy.ent_perc AS ent_pct,
spy.pos_adj_perc AS pos_adj_pct, 
spy.pos_adj_count AS pos_adj_cnt,
spy.pos_adp_perc AS pos_adp_pct,
spy.pos_adp_count AS pos_adp_cnt,
spy.pos_adv_perc AS pos_adv_pct,
spy.pos_adv_count AS pos_adv_cnt,
spy.pos_aux_perc AS pos_aux_pct,
spy.pos_aux_count AS pos_aux_cnt,
spy.pos_conj_perc AS pos_conj_pct,
spy.pos_conj_count AS pos_conj_cnt,
spy.pos_det_perc AS pos_det_pct,
spy.pos_det_count AS pos_det_cnt,
spy.pos_intj_perc AS pos_intj_pct,
spy.pos_intj_count AS pos_intj_cnt,
spy.pos_noun_perc AS pos_noun_pct,
spy.pos_noun_count AS pos_noun_cnt,
spy.pos_num_perc AS pos_num_pct,
spy.pos_num_count AS pos_num_cnt,
spy.pos_part_perc AS pos_part_pct,
spy.pos_part_count AS pos_part_cnt,
spy.pos_pron_perc AS pos_pron_pct, 
spy.pos_pron_count AS pos_pron_cnt,
spy.pos_propn_perc AS pos_propn_pct,
spy.pos_propn_count AS pos_propn_cnt,
spy.pos_punct_perc AS pos_punct_pct,
spy.pos_punct_count AS pos_punct_cnt,
spy.pos_sconj_perc AS pos_sconj_pct,
spy.pos_sconj_count AS pos_sconj_cnt,
spy.pos_sym_perc AS pos_sym_pct, 
spy.pos_sym_count AS pos_sym_cnt,
spy.pos_verb_perc AS pos_verb_pct,
spy.pos_verb_count AS pos_verb_cnt,
spy.pos_x_perc AS pos_x_pct,   
spy.pos_x_count AS pos_x_cnt,  
spy.dep_root_perc AS dep_root_pct,
spy.dep_root_count AS dep_root_cnt,
spy.dep_acl_perc AS dep_acl_pct, 
spy.dep_acl_count AS dep_acl_cnt,
spy.dep_acomp_perc AS dep_acomp_pct,
spy.dep_acomp_count AS dep_acomp_cnt,
spy.dep_advcl_perc AS dep_advcl_pct,
spy.dep_advcl_count AS dep_advcl_cnt,
spy.dep_advmod_perc AS dep_advmod_pct, 
spy.dep_advmod_count AS dep_advmod_cnt,
spy.dep_agent_perc AS dep_agent_pct,  
spy.dep_agent_count AS dep_agent_cnt, 
spy.dep_amod_perc AS dep_amod_pct,   
spy.dep_amod_count AS dep_amod_cnt,   
spy.dep_appos_perc AS dep_appos_pct,  
spy.dep_appos_count AS dep_appos_cnt,   
spy.dep_attr_perc AS dep_attr_pct,    
spy.dep_attr_count AS dep_attr_cnt,  
spy.dep_aux_perc AS dep_aux_pct,     
spy.dep_aux_count AS dep_aux_cnt,   
spy.dep_auxpass_perc AS dep_auxpass_pct,
spy.dep_auxpass_count AS dep_auxpass_cnt,
spy.dep_case_perc AS dep_case_pct,   
spy.dep_case_count AS dep_case_cnt,  
spy.dep_cc_perc AS dep_cc_pct,     
spy.dep_cc_count AS dep_cc_cnt,    
spy.dep_ccomp_perc AS dep_ccomp_pct,  
spy.dep_ccomp_count AS dep_ccomp_cnt, 
spy.dep_compound_perc AS dep_compound_pct,
spy.dep_compound_count AS dep_compound_cnt,
spy.dep_conj_perc AS dep_conj_pct,    
spy.dep_conj_count AS dep_conj_cnt,   
spy.dep_csubj_perc AS dep_csubj_pct,   
spy.dep_csubj_count AS dep_csubj_cnt,  
spy.dep_csubjpass_perc AS dep_csubjpass_pct,
spy.dep_csubjpass_count AS dep_csubjpass_cnt,
spy.dep_dative_perc AS dep_dative_pct,  
spy.dep_dative_count AS dep_dative_cnt, 
spy.dep_dep_perc AS dep_dep_pct,     
spy.dep_dep_count AS dep_dep_cnt,    
spy.dep_det_perc AS dep_det_pct,     
spy.dep_det_count AS dep_det_cnt,    
spy.dep_dobj_perc AS dep_dobj_pct,    
spy.dep_dobj_count AS dep_dobj_cnt,   
spy.dep_expl_perc AS dep_expl_pct,    
spy.dep_expl_count AS dep_expl_cnt,   
spy.dep_intj_perc AS dep_intj_pct,    
spy.dep_intj_count AS dep_intj_cnt,   
spy.dep_mark_perc AS dep_mark_pct,    
spy.dep_mark_count AS dep_mark_cnt,   
spy.dep_meta_perc AS dep_meta_pct,    
spy.dep_meta_count AS dep_meta_cnt,   
spy.dep_neg_perc AS dep_neg_pct,     
spy.dep_neg_count AS dep_neg_cnt,    
spy.dep_nmod_perc AS dep_nmod_pct,    
spy.dep_nmod_count AS dep_nmod_cnt,   
spy.dep_npadvmod_perc AS dep_npadvmod_pct,
spy.dep_npadvmod_count AS dep_npadvmod_cnt,
spy.dep_nsubj_perc AS dep_nsubj_pct,   
spy.dep_nsubj_count AS dep_nsubj_cnt,  
spy.dep_nsubjpass_perc AS dep_nsubjpass_pct,
spy.dep_nsubjpass_count AS dep_nsubjpass_cnt,
spy.dep_nummod_perc AS dep_nummod_pct,  
spy.dep_nummod_count AS dep_nummod_cnt, 
spy.dep_oprd_perc AS dep_oprd_pct,    
spy.dep_oprd_count AS dep_oprd_cnt,   
spy.dep_parataxis_perc AS dep_parataxis_pct,
spy.dep_parataxis_count AS dep_parataxis_cnt,
spy.dep_pcomp_perc AS dep_pcomp_pct,   
spy.dep_pcomp_count AS dep_pcomp_cnt,  
spy.dep_pobj_perc AS dep_pobj_pct,    
spy.dep_pobj_count AS dep_pobj_cnt,   
spy.dep_poss_perc AS dep_poss_pct,    
spy.dep_poss_count AS dep_poss_cnt,   
spy.dep_preconj_perc AS dep_preconj_pct,
spy.dep_preconj_count AS dep_preconj_cnt,
spy.dep_predet_perc AS dep_predet_pct, 
spy.dep_predet_count AS dep_predet_cnt,
spy.dep_prep_perc AS dep_prep_pct,   
spy.dep_prep_count AS dep_prep_cnt,  
spy.dep_prt_perc AS dep_prt_pct,    
spy.dep_prt_count AS dep_prt_cnt,   
spy.dep_punct_perc AS dep_punct_pct,  
spy.dep_punct_count AS dep_punct_cnt, 
spy.dep_quantmod_perc AS dep_quantmod_pct,
spy.dep_quantmod_count AS dep_quantmod_cnt,
spy.dep_relcl_perc AS dep_relcl_pct,   
spy.dep_relcl_count AS dep_relcl_cnt, 
spy.dep_xcomp_perc AS dep_xcomp_pct,  
spy.dep_xcomp_count AS dep_xcomp_cnt, 
spy.ent_cardinal_perc AS ent_cardinal_pct,
spy.ent_cardinal_count AS ent_cardinal_cnt,
spy.ent_date_perc AS ent_date_pct,   
spy.ent_date_count AS ent_date_cnt,  
spy.ent_event_perc AS ent_event_pct,  
spy.ent_event_count AS ent_event_cnt, 
spy.ent_fac_perc AS ent_fac_pct,    
spy.ent_fac_count AS ent_fac_cnt,   
spy.ent_gpe_perc AS ent_gpe_pct,    
spy.ent_gpe_count AS ent_gpe_cnt,   
spy.ent_language_perc AS ent_language_pct,
spy.ent_language_count AS ent_language_cnt,
spy.ent_law_perc AS ent_law_pct,    
spy.ent_law_count AS ent_law_cnt,   
spy.ent_loc_perc AS ent_loc_pct,    
spy.ent_loc_count AS ent_loc_cnt,   
spy.ent_money_perc AS ent_money_pct,  
spy.ent_money_count AS ent_money_cnt, 
spy.ent_norp_perc AS ent_norp_pct,   
spy.ent_norp_count AS ent_norp_cnt,  
spy.ent_ordinal_perc AS ent_ordinal_pct,
spy.ent_ordinal_count AS ent_ordinal_cnt,
spy.ent_org_perc AS ent_org_pct,    
spy.ent_org_count AS ent_org_cnt,   
spy.ent_percent_perc AS ent_percent_pct, 
spy.ent_percent_count AS ent_percent_cnt,
spy.ent_person_perc AS ent_person_pct, 
spy.ent_person_count AS ent_person_cnt,
spy.ent_product_perc AS ent_product_pct,
spy.ent_product_count AS ent_product_cnt,  
spy.ent_quantity_perc AS ent_quantity_pct,  
spy.ent_quantity_count AS ent_quantity_cnt, 
spy.ent_time_perc AS ent_time_pct,      
spy.ent_time_count AS ent_time_cnt,     
spy.ent_work_of_art_perc AS ent_work_of_art_pct,
spy.ent_work_of_art_count AS ent_work_of_art_cnt
INTO text_combined_train
FROM text_data_train AS orig
JOIN text_basic_train AS base
ON orig.review_id = base.review_id
JOIN text_spacy_train AS spy
ON orig.review_id = spy.review_id
JOIN text_nb_train AS nb
ON orig.review_id = nb.review_id
JOIN text_svm_train AS svm
ON orig.review_id = svm.review_id
JOIN text_fasttext_train AS ft
ON orig.review_id = ft.review_id
JOIN text_lda_train AS lda
ON orig.review_id = lda.review_id;

-- Changing to smaller datatypes

ALTER TABLE text_combined_train
ALTER COLUMN ent_work_of_art_cnt TYPE smallint,
ALTER COLUMN target_reg TYPE smallint,
ALTER COLUMN review_stars TYPE smallint,
ALTER COLUMN NB_prob TYPE real,
ALTER COLUMN svm_pred TYPE real,
ALTER COLUMN ft_prob TYPE real,
ALTER COLUMN lda_t1 TYPE real,
ALTER COLUMN lda_t2 TYPE real,
ALTER COLUMN lda_t3 TYPE real,
ALTER COLUMN lda_t4 TYPE real,
ALTER COLUMN lda_t5 TYPE real,
ALTER COLUMN grade_level TYPE real,
ALTER COLUMN polarity TYPE real,
ALTER COLUMN subjectivity TYPE real,
ALTER COLUMN word_cnt TYPE smallint,
ALTER COLUMN character_cnt TYPE smallint,
ALTER COLUMN num_cnt TYPE smallint,
ALTER COLUMN uppercase_cnt TYPE smallint,
ALTER COLUMN #@_cnt TYPE smallint,
ALTER COLUMN sentence_cnt TYPE smallint,
ALTER COLUMN lexicon_cnt TYPE smallint,
ALTER COLUMN syllable_cnt TYPE smallint,
ALTER COLUMN avg_word_len TYPE real,
ALTER COLUMN token_cnt TYPE smallint,
ALTER COLUMN stopword_cnt TYPE smallint,
ALTER COLUMN stopword_pct TYPE real,
ALTER COLUMN ent_cnt TYPE smallint,
ALTER COLUMN ent_pct TYPE real,
ALTER COLUMN pos_adj_pct TYPE real,
ALTER COLUMN pos_adj_cnt TYPE smallint,
ALTER COLUMN pos_adp_pct TYPE real,
ALTER COLUMN pos_adp_cnt TYPE smallint,
ALTER COLUMN pos_adv_pct TYPE real,
ALTER COLUMN pos_adv_cnt TYPE smallint,
ALTER COLUMN pos_aux_pct TYPE real,
ALTER COLUMN pos_aux_cnt TYPE smallint,
ALTER COLUMN pos_conj_pct TYPE real,
ALTER COLUMN pos_conj_cnt TYPE smallint,
ALTER COLUMN pos_det_pct TYPE real,
ALTER COLUMN pos_det_cnt TYPE smallint,
ALTER COLUMN pos_intj_pct TYPE real,
ALTER COLUMN pos_intj_cnt TYPE smallint,
ALTER COLUMN pos_noun_pct TYPE real,
ALTER COLUMN pos_noun_cnt TYPE smallint,
ALTER COLUMN pos_num_pct TYPE real,
ALTER COLUMN pos_num_cnt TYPE smallint,
ALTER COLUMN pos_part_pct TYPE real,
ALTER COLUMN pos_part_cnt TYPE smallint,
ALTER COLUMN pos_pron_pct TYPE real,
ALTER COLUMN pos_pron_cnt TYPE smallint,
ALTER COLUMN pos_propn_pct TYPE real,
ALTER COLUMN pos_propn_cnt TYPE smallint,
ALTER COLUMN pos_punct_pct TYPE real,
ALTER COLUMN pos_punct_cnt TYPE smallint,
ALTER COLUMN pos_sconj_pct TYPE real,
ALTER COLUMN pos_sconj_cnt TYPE smallint,
ALTER COLUMN pos_sym_pct TYPE real,
ALTER COLUMN pos_sym_cnt TYPE smallint,
ALTER COLUMN pos_verb_pct TYPE real,
ALTER COLUMN pos_verb_cnt TYPE smallint,
ALTER COLUMN pos_x_pct TYPE real,
ALTER COLUMN pos_x_cnt TYPE smallint,
ALTER COLUMN dep_root_pct TYPE real,
ALTER COLUMN dep_root_cnt TYPE smallint,
ALTER COLUMN dep_acl_pct TYPE real,
ALTER COLUMN dep_acl_cnt TYPE smallint,
ALTER COLUMN dep_acomp_pct TYPE real,
ALTER COLUMN dep_acomp_cnt TYPE smallint,
ALTER COLUMN dep_advcl_pct TYPE real,
ALTER COLUMN dep_advcl_cnt TYPE smallint,
ALTER COLUMN dep_advmod_pct TYPE real,
ALTER COLUMN dep_advmod_cnt TYPE smallint,
ALTER COLUMN dep_agent_pct TYPE real,
ALTER COLUMN dep_agent_cnt TYPE smallint,
ALTER COLUMN dep_amod_pct TYPE real,
ALTER COLUMN dep_amod_cnt TYPE smallint,
ALTER COLUMN dep_appos_pct TYPE real,
ALTER COLUMN dep_appos_cnt TYPE smallint,
ALTER COLUMN dep_attr_pct TYPE real,
ALTER COLUMN dep_attr_cnt TYPE smallint,
ALTER COLUMN dep_aux_pct TYPE real,
ALTER COLUMN dep_aux_cnt TYPE smallint,
ALTER COLUMN dep_auxpass_pct TYPE real,
ALTER COLUMN dep_auxpass_cnt TYPE smallint,
ALTER COLUMN dep_case_pct TYPE real,
ALTER COLUMN dep_case_cnt TYPE smallint,
ALTER COLUMN dep_cc_pct TYPE real,
ALTER COLUMN dep_cc_cnt TYPE smallint,
ALTER COLUMN dep_ccomp_pct TYPE real,
ALTER COLUMN dep_ccomp_cnt TYPE smallint,
ALTER COLUMN dep_compound_pct TYPE real,
ALTER COLUMN dep_compound_cnt TYPE smallint,
ALTER COLUMN dep_conj_pct TYPE real,
ALTER COLUMN dep_conj_cnt TYPE smallint,
ALTER COLUMN dep_csubj_pct TYPE real,
ALTER COLUMN dep_csubj_cnt TYPE smallint,
ALTER COLUMN dep_csubjpass_pct TYPE real,
ALTER COLUMN dep_csubjpass_cnt TYPE smallint,
ALTER COLUMN dep_dative_pct TYPE real,
ALTER COLUMN dep_dative_cnt TYPE smallint,
ALTER COLUMN dep_dep_pct TYPE real,
ALTER COLUMN dep_dep_cnt TYPE smallint,
ALTER COLUMN dep_det_pct TYPE real,
ALTER COLUMN dep_det_cnt TYPE smallint,
ALTER COLUMN dep_dobj_pct TYPE real,
ALTER COLUMN dep_dobj_cnt TYPE smallint,
ALTER COLUMN dep_expl_pct TYPE real,
ALTER COLUMN dep_expl_cnt TYPE smallint,
ALTER COLUMN dep_intj_pct TYPE real,
ALTER COLUMN dep_intj_cnt TYPE smallint,
ALTER COLUMN dep_mark_pct TYPE real,
ALTER COLUMN dep_mark_cnt TYPE smallint,
ALTER COLUMN dep_meta_pct TYPE real,
ALTER COLUMN dep_meta_cnt TYPE smallint,
ALTER COLUMN dep_neg_pct TYPE real,
ALTER COLUMN dep_neg_cnt TYPE smallint,
ALTER COLUMN dep_nmod_pct TYPE real,
ALTER COLUMN dep_nmod_cnt TYPE smallint,
ALTER COLUMN dep_npadvmod_pct TYPE real,
ALTER COLUMN dep_npadvmod_cnt TYPE smallint,
ALTER COLUMN dep_nsubj_pct TYPE real,
ALTER COLUMN dep_nsubj_cnt TYPE smallint,
ALTER COLUMN dep_nsubjpass_pct TYPE real,
ALTER COLUMN dep_nsubjpass_cnt TYPE smallint,
ALTER COLUMN dep_nummod_pct TYPE real,
ALTER COLUMN dep_nummod_cnt TYPE smallint,
ALTER COLUMN dep_oprd_pct TYPE real,
ALTER COLUMN dep_oprd_cnt TYPE smallint,
ALTER COLUMN dep_parataxis_pct TYPE real,
ALTER COLUMN dep_parataxis_cnt TYPE smallint,
ALTER COLUMN dep_pcomp_pct TYPE real,
ALTER COLUMN dep_pcomp_cnt TYPE smallint,
ALTER COLUMN dep_pobj_pct TYPE real,
ALTER COLUMN dep_pobj_cnt TYPE smallint,
ALTER COLUMN dep_poss_pct TYPE real,
ALTER COLUMN dep_poss_cnt TYPE smallint,
ALTER COLUMN dep_preconj_pct TYPE real,
ALTER COLUMN dep_preconj_cnt TYPE smallint,
ALTER COLUMN dep_predet_pct TYPE real,
ALTER COLUMN dep_predet_cnt TYPE smallint,
ALTER COLUMN dep_prep_pct TYPE real,
ALTER COLUMN dep_prep_cnt TYPE smallint,
ALTER COLUMN dep_prt_pct TYPE real,
ALTER COLUMN dep_prt_cnt TYPE smallint,
ALTER COLUMN dep_punct_pct TYPE real,
ALTER COLUMN dep_punct_cnt TYPE smallint,
ALTER COLUMN dep_quantmod_pct TYPE real,
ALTER COLUMN dep_quantmod_cnt TYPE smallint,
ALTER COLUMN dep_relcl_pct TYPE real,
ALTER COLUMN dep_relcl_cnt TYPE smallint,
ALTER COLUMN dep_xcomp_pct TYPE real,
ALTER COLUMN dep_xcomp_cnt TYPE smallint,
ALTER COLUMN ent_cardinal_pct TYPE real,
ALTER COLUMN ent_cardinal_cnt TYPE smallint,
ALTER COLUMN ent_date_pct TYPE real,
ALTER COLUMN ent_date_cnt TYPE smallint,
ALTER COLUMN ent_event_pct TYPE real,
ALTER COLUMN ent_event_cnt TYPE smallint,
ALTER COLUMN ent_fac_pct TYPE real,
ALTER COLUMN ent_fac_cnt TYPE smallint,
ALTER COLUMN ent_gpe_pct TYPE real,
ALTER COLUMN ent_gpe_cnt TYPE smallint,
ALTER COLUMN ent_language_pct TYPE real,
ALTER COLUMN ent_language_cnt TYPE smallint,
ALTER COLUMN ent_law_pct TYPE real,
ALTER COLUMN ent_law_cnt TYPE smallint,
ALTER COLUMN ent_loc_pct TYPE real,
ALTER COLUMN ent_loc_cnt TYPE smallint,
ALTER COLUMN ent_money_pct TYPE real,
ALTER COLUMN ent_money_cnt TYPE smallint,
ALTER COLUMN ent_norp_pct TYPE real,
ALTER COLUMN ent_norp_cnt TYPE smallint,
ALTER COLUMN ent_ordinal_pct TYPE real,
ALTER COLUMN ent_ordinal_cnt TYPE smallint,
ALTER COLUMN ent_org_pct TYPE real,
ALTER COLUMN ent_org_cnt TYPE smallint,
ALTER COLUMN ent_percent_pct TYPE real,
ALTER COLUMN ent_percent_cnt TYPE smallint,
ALTER COLUMN ent_person_pct TYPE real,
ALTER COLUMN ent_person_cnt TYPE smallint,
ALTER COLUMN ent_product_pct TYPE real,
ALTER COLUMN ent_product_cnt TYPE smallint,
ALTER COLUMN ent_quantity_pct TYPE real,
ALTER COLUMN ent_quantity_cnt TYPE smallint,
ALTER COLUMN ent_time_pct TYPE real,
ALTER COLUMN ent_time_cnt TYPE smallint,
ALTER COLUMN ent_work_of_art_pct TYPE real;

-- Add Primary Key

ALTER TABLE text_data_train ADD PRIMARY KEY (review_id);
